"""Multi-format export utilities for generated data."""

from __future__ import annotations

import csv
import json
from pathlib import Path


class Exporter:
    """Export records (list of dicts) to various formats."""

    @staticmethod
    def to_json(records: list[dict], path: str | Path, indent: int = 2) -> None:
        """Export records to a JSON file."""
        Path(path).write_text(
            json.dumps(records, ensure_ascii=False, indent=indent),
            encoding="utf-8",
        )

    @staticmethod
    def to_csv(records: list[dict], path: str | Path) -> None:
        """Export records to a CSV file."""
        if not records:
            return
        fieldnames = list(records[0].keys())
        with open(path, "w", newline="", encoding="utf-8-sig") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(records)

    @staticmethod
    def to_sql(
        records: list[dict],
        table_name: str,
        path: str | Path,
    ) -> None:
        """Export records as SQL INSERT statements."""
        if not records:
            return
        columns = list(records[0].keys())
        col_str = ", ".join(columns)
        lines = ["-- Generated by nlpFaker\n"]
        for record in records:
            values = []
            for col in columns:
                val = record[col]
                if val is None:
                    values.append("NULL")
                elif isinstance(val, (int, float)):
                    values.append(str(val))
                else:
                    escaped = str(val).replace("'", "''")
                    values.append(f"'{escaped}'")
            val_str = ", ".join(values)
            lines.append(f"INSERT INTO {table_name} ({col_str}) VALUES ({val_str});\n")
        Path(path).write_text("".join(lines), encoding="utf-8")
